# Generated by Django 4.0.5 on 2022-06-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_useradmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradmin',
            name='userlogin',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
