# Generated by Django 4.0.5 on 2022-06-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='phonenumber',
            field=models.IntegerField(max_length=200),
        ),
    ]
