# Generated by Django 4.0.5 on 2022-06-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_alter_subscribers_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='subscribers',
            name='phonenumber',
        ),
    ]
